services:
  - type: web
    name: markdcommerce
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn markdcommerce.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: markdcommerce_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: markdcommerce_db
    databaseName: markdcommerce
    user: markdcommerce