# Generated by Django 5.1.6 on 2025-02-27 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_cartitem_created_at_cartitem_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 27, 20, 3, 16, 961024, tzinfo=datetime.timezone.utc)),
        ),
    ]
