# Generated by Django 5.1.6 on 2025-02-28 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_cartitem_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 7, 42, 11, 541517, tzinfo=datetime.timezone.utc)),
        ),
    ]
