# Generated by Django 5.1.6 on 2025-02-28 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_cartitem_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 10, 18, 44, 330171, tzinfo=datetime.timezone.utc)),
        ),
    ]
