# Generated by Django 5.1.6 on 2025-02-28 12:23

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_cartitem_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cloudinary_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 12, 23, 47, 340322, tzinfo=datetime.timezone.utc)),
        ),
    ]
