# Generated by Django 5.1.6 on 2025-02-28 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_cloudinary_image_alter_cartitem_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 12, 57, 57, 410807, tzinfo=datetime.timezone.utc)),
        ),
    ]
