# Generated by Django 5.1.6 on 2025-02-28 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_cartitem_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cloudinary_image',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 13, 23, 25, 436089, tzinfo=datetime.timezone.utc)),
        ),
    ]
