# Generated by Django 5.1.6 on 2025-02-28 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_remove_product_cloudinary_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 19, 38, 28, 317550, tzinfo=datetime.timezone.utc)),
        ),
    ]
