# Generated by Django 5.1.6 on 2025-03-01 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_cartitem_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 1, 13, 11, 53, 123963, tzinfo=datetime.timezone.utc)),
        ),
    ]
